language: java

jdk:
- oraclejdk8

branches:
  only:
    - master
  
before_install:
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar https://github.com/codacy/codacy-coverage-reporter/releases/download/4.0.1/codacy-coverage-reporter-4.0.1-assembly.jar

after_success:
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/site/jacoco/jacoco.xml

deploy:
  provider: script
  script: mvn deploy --settings .travis.settings.xml
  skip_cleanup: true

env:
  global:
  - secure: uANaFe1KyemfWMaaCwOOSZGfbW/UtM/JZ531RS29uGwJJHSV8cVF/wFpw5QuKSCYbV2cQFlJtv2YRQZCJORO/5Mk5F72S/Jf9zb8HWI5kRKg95TgNgOjtkTX3B0efZxE1Yh2v+w60BeMIQTPXvRNhZ0CpsOMMqeI4xb9nY0CmpJMq5lLA5PwGUNY9PoCoWkdJzy3goPD7x234paKvhwc075yomee8T3fWZoK8FjCGVba1hWTvIpJ4hKEf2+WtoucS4iUKEDkORU6xZd9/JI7XGFGWtDxXUx6MqH8qYwSEwakLfij/q5dIrE73cP8MP6246RcIM2d3Tq043HZKod/PkN+Q0vKmABVjLI2VhfBvhYBCHle3eJYafodCIhAQqJcVf5KpAjwlPGlLbvrmFHw1+cAboFCnQGqRKvT73HuuOx3KXCz2yf98wNTgfYAPFd4pFtNPXCjWnJJAXdo2mZahlFflU6+ys3XPl+bVu41wGu0XCDRTcTkigRsONKkj+gLWgG9W4Bisd5sllzVFP49TFfXruMjPFgAWJQl9h8pxcSu5pwQLYiDHNuVChtRKAlwLzri83xbxvwtktZ2Ya9VNU2VZVL2N0ssrnkwBx3buNe1dlrbVVOsWfxos0oZ4ZPpDKKO/ysYckjRsDxjl/O4KqlsXNosnkuiI4w5QX36pq0=
  - secure: O+zW8JATmZ52LfUOJKMY0XREtVFGfu4WCfbauuGkECexsjVcggs2ctXp6PPAIuq0NdpuuE9+aVaY6/ZSAbt72q2hh8mKicpvMKHhXpoBv857olIESmuidqcJl/pR2oZH20+kTUoD1kJiG48o8ZBSSiAL9+QFwDhI2d9qGSCmbQ+aljDr1Vi/sexOWb7yebQXn767q3syS42tJ8UotCP2SdX0imPF7Sh25UpORNF3hUc0ldGMCxUF4LchJcdkhgbsxxsqNbWkjQE62j50fJIyKmBKXphl0hB7+V9dVjejvQ6FTf0Y1RrWHiwvWw0R75pntlkx3KERDHRN7WlwGNezB+ftfxV+btgn0w21CE0EPmb+bjjVM8jlJntyuISs2ZulqXgq0SBSvSM8IU0e6TZge4bR+Ad+Lnj7KEBKeb5Zpy90svrCXkYwxVqySumMdCIOVMqPmbp2HmV51tGvEZQ6yUvFYm3ZVz+a0ptDT40lUumL1Xf4iLipJHejBAjCE9+kNq2ODoi4aYnMtWhZcVDyy5kVR3UkXAiy+LJv2SxhbQLSoKPRe79Au1iYZ8KURDIidlDfIzHdauUZ2DqMi9pk4s2ly6YU74pr66mFk6q8X86KsqHCVMNm4IVSjIR20rRUnmypXfZiUh78xZsrQ4GpeF8IqiuPpNdStUhoN4DmF28=
